[package]
name = "euler-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = "1.1.3"
codegen = "0.1.3"
scraper = "0.20.0"
html2text = "0.12.5"
reqwest = { version = "0.12.7", features = ["blocking"] }
clap = { version = "4.0", features = ["derive"] }
