[package]
name = "euler-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
codegen = "0.1.3"
scraper = "0.20.0"
reqwest = {version = "0.11", features = ["blocking"]}
clap = { version = "4.0", features = ["derive"] }
